### ISSUE TITLE
MangaDex loading slow

### ISSUE THREAD

**Issue by metroid112** [fuzetsu/manga-loader#23]
For some reason while using the script with MangaDex the pages are loading extremely slow, while if you browse the manga through normal means the loading is way faster.

**Comment by fuaxio** [comment]
Images are not loading slow.
Only the first two images are loading instead of the entire set of images.

**Comment by metroid112** [comment]
![image](https://user-images.githubusercontent.com/9469239/36102809-38542f86-0fec-11e8-9aad-5b9c28834243.png)

For me it eventually loads them but I leave the tab open for a few minutes to do other stuff while I wait.

**Comment by kyuucr** [comment]
The guy who makes mangadex's config here, I tried to make my code more concise, yet the problem persist. IMO it loads the images one at a time because the script needs to load the viewer page for each image, and mangadex's viewer page is absurdly heavy to load. They designed the viewer page full of scripts, only swapping the current image element with next images so that the heavy load is only at the start. If we can directly load the image instead through the viewer page, it may be as fast as loading it through normal means.  I'd say just use their normal viewer, we may not be able to be faster than theirs.

**Comment by metroid112** [comment]
Yeah thankfully they implemented a webtoon-like viewer now so it's the best choice for now. It would be nice to improve the loading process but I guess we'll wait.

**Comment by Chibicon** [comment]
The problem with their viewer is that they are resizing the images pretty hard. It's extremely noticeable on wide/double pages.

**Comment by kyuucr** [comment]
So when manga-loader loads a page, does it run the page script? Can we disable that and just extract the elements we need?
cc: @fuzetsu

**Comment by fuzetsu** [comment]
It shouldn't run the pages scripts, and even if the page is heavy it shouldn't be that much heavier than loading an image or something, the responses could be slow maybe. The `pages` method can be used in an implementation to implement a custom way of loading the pages, so you could code it to preload everything instead of going sequentially, but I don't know if that would be the best solution.

**Comment by kyuucr** [comment]
So I noticed that the script loads faster now, coincidentally, [they upgraded their servers](https://mangadex.org/changelog). So we can conclude that it's not the script that loads slowly, but their server was slow anyway.

**Comment by fuzetsu** [comment]
Fixed by #27 , thanks @kyuucr
