### ISSUE TITLE
mangadex.org

### ISSUE THREAD

**Issue by aaaplus1** [fuzetsu/manga-loader#26]
changed domain to .org and their reader code is changed, replacing URL match inside the script doesn't work

**Comment by unluckydog** [comment]
As above, needs update for Mangadex.

**Comment by kyuucr** [comment]
Working on it

**Comment by fuzetsu** [comment]
Fixed by #27

**Comment by aaaplus1** [comment]
Actually, you should remove it from the next version, this style of implementation is likely to get you IPbanned.

**Comment by kyuucr** [comment]
Any reason why? I properly open each page to load, then properly retrieves the image element from the page. I thought you get IP banned if you're scraping the image directly without opening the page, since I've did that out of curiosity and got banned temporarily.

Any suggestion on which part you think needs to be fixed is really appreciated :)

**Comment by aaaplus1** [comment]
According to the mods, loading multiple pages at once is likely to get you banned. I was probably opening 5 chapters of 20 pages and got banned. Didn't know if it was temp or not since I got unbanned by PM. They did suggest an array of sorts might have worked better, but you say that got you a tempban, soooo, shrugs.

**The point is moot since they have their own built in vertical reader, so it'd be better to remove it.** 
Would have been nice if I knew about it before I opened this issue, hahaha.

**Comment by kyuucr** [comment]
I see, I think it is rational if you got banned from loading 100 images at once. Since it's really hard to differentiate scraping from heavy use from normal user, it's common to just limit how much images a user can request at a time. I also want to clarify that I got temp ban on an earlier version of mangadex, and I think it was from the cloudflare not the mangadex server, so my case might be different from yours.

I don't think having this implementation is moot, since this script offer more options than the current built in vertical reader. What's moot is that they enabled vertical reader that loads all of images in a chapter at once, but ban user from loading too much images. At least this script has an option for limiting load. So far I haven't got banned from using this script.

**Comment by aaaplus1** [comment]
It was the cloudflare ban, if that makes any real difference. They specifically said your current implementation was likely to get bans. 

I had tabs set to delays so it was more of a case of 20pages every few minutes.

Well, if you don't feel like removing it, I can just block it locally.

**Comment by kyuucr** [comment]
OK, I get the problem now, but I'm not convinced yet, I think I need to hear more report on this. Thanks for your input! :)
